### ISSUE TITLE
Simple rebinds not working

### ISSUE THREAD

**Issue by logix2** [snyball/Hawck#12]
I'm trying to use Hawck in Ubuntu 19.04, so I ran the GUI and on the Simple Rebind tab, the delete and add buttons don't do anything. Also, when I start hawck-ui (might be related), I get this terminal output:

```
$ hawck-ui

6711
6782
<hawck_ui.window.Settings object at 0x7fe9fbac6e48> autostart_switch False
<hawck_ui.window.Settings object at 0x7fe9fbac6e48> unsafe_mode_switch False
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/hawck_ui-0.6-py3.7.egg/hawck_ui/main.py", line 54, in do_activate
    self.window = HawckMainWindow(application=self, version=self.version)
  File "/usr/local/lib/python3.7/dist-packages/hawck_ui-0.6-py3.7.egg/hawck_ui/window.py", line 355, in __init__
    self.settings = Settings(builder = self.builder)
  File "/usr/local/lib/python3.7/dist-packages/hawck_ui-0.6-py3.7.egg/hawck_ui/window.py", line 228, in __init__
    self.setCheck(f"{chk}_chk", sendMacroD(f"return config.{chk}")[0])
  File "/usr/local/lib/python3.7/dist-packages/hawck_ui-0.6-py3.7.egg/hawck_ui/cfgmsg.py", line 17, in sendcfg
    return json.loads(json_str)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by snyball** [comment]
Did you start `hawck-inputd` and `hawck-macrod`? Also, remember, macrod should run as your regular user account.

**Comment by logix2** [comment]
Yes I started both services, and hawck-ui shows both of them as running. As for the user, the readme says "You will need to reboot the computer after running the installer, because it needs to add your user to a new group (with Ubuntu it seems like logging out and back in isn't enough.)", so I rebooted after installing, then started the services. Do I need to do anything else?
